---
title: "5.2 Feature Tuning/Selection"
output: html_notebook
---


# Feature Tuning

TODO: Feature selection


## Multi-colinearity in BE cols
Dealing with Multi-colinearity, winnowing down the variable list
```{r}
# Test cols
BE_cols.std[!str_detect(BE_cols.std, 'Missing')]
data %>% 
  filter(daily_vmt < 300, !is.infinite(NetLoadDens_GF18_two)) %>%
  select(any_of(do.call(paste, c(expand.grid(BE_cols.std, BE_suffixes), sep='_')))) %>% 
  select(-c(ends_with(paste0('Wage','_', geo_level)), starts_with('Missing'))) %>%
  cor() %>% 
  as_tibble(rownames = 'var1') %>%
  pivot_longer(cols = -var1, names_to = 'var2', values_to ='corr') %>%
  arrange(desc(corr)) %>%
  filter(corr != 1) %>%
  extract(var1, into = c('var1', 'geo'),'(.*)_([^_]+$)') %>%
  ggplot(aes(x = corr)) + 
  stat_bin(bins=10) + 
  facet_wrap(~geo)
  
df.just_BE_std <- data %>% 
  filter(daily_vmt < 300, !is.infinite(NetLoadDens_GF18_two)) %>%
  select(
    daily_vmt, any_of(do.call(paste, c(expand.grid(BE_cols.std, BE_suffixes), sep='_')))) %>% 
  select(-c(
    ends_with(paste0('Wage','_', BE_suffixes)), 
    starts_with('Missing'),
    starts_with('PubDens')
  ))

model.just_BE_std <- AER::tobit(as.formula(paste0('daily_vmt ~', paste(names(select(df.just_BE_std, -daily_vmt)), collapse = '+'))), left = 0, data = df.just_BE_std)
#car::vif()

any(is.na(coef(model.just_BE_std)))
summary(model.just_BE_std)

vif.just_BE_std <- car::vif(model.just_BE_std) %>% as_tibble(rownames = 'var')

vif.just_BE_std <- 
  vif.just_BE_std %>%
  extract(var, into = c('var', 'geo'), '(.*)_([^_]+$)')

vif.just_BE_std %>%
  arrange(desc(value)) %>%
  print(n = 60)

max_vif <- 5
vif.just_BE_std%>%
  ggplot(aes(y = as_factor(var), x = value)) + 
  geom_bar(stat = 'identity') + 
  theme(
    axis.text.x = element_text(angle = 30, hjust = .6, vjust = .6, size = 9),
  ) + 
  scale_x_log10() + 
  labs(
    title = 'Variance Inflation Test of Built-Env Characteristics',
    y = NULL,
    x = NULL
  ) + 
  geom_vline(xintercept = max_vif, color = 'red') + 
  facet_wrap(~geo)
```

## Test each BE Var for best 


# Model Building

## (6.5) Initial build with everything
```{r intial model build} 
library(fastDummies)
# Dummify
df.dummies <- df.clean %>% 
  # filter(
  #   age_OE___NotMissing == 1,
  # ) %>%
  select(-cbsa_code, -cbsa_title) %>%
  dummy_cols(remove_selected_columns = TRUE, )

# Set Features to use
vars <- names(select(df.dummies, -dv))
vars_to_ignore <- c('hhincome_cat_12: Missing Data','age_bucket_Missing','race_White','race_consolidated_AAPI','race_consolidated_AfAm','race_consolidated_AI_Other_Multiple','race_consolidated_Missing', 'race_consolidated_Other_Multiple_Missing','race_consolidated_White','education_Missing','homeown_Rent','sex_Missing','sex_consolidated_Male','sex_consolidated_Not_Male')
vars <- vars[vars %notin% vars_to_ignore]
vars <- tail(vars, 50)

# Build Formula
form <- as.formula(paste0(dv, ' ~ ',  '`', paste0(vars, collapse = '`+`'), '`'))

# Run Model
model <- AER::tobit(form, left = 0, data=df.dummies)
summary(model)

coef(model)

# Check aliased coefficients
paste0(names(coef(model)[is.na(coef(model))]), collapse="','")
```

## Feature Selection
```{r initial-feature-selection}


```

### Demographic Controls
```{r}
demos.bucket_type <- 'open_ended' # one of c('discrete', 'continuous', 'open_ended')
demos.consolidate_vars <- TRUE # Use slimmer versions of columns

demo_controls <- c(
  # Age 
  switch(demos.bucket_type, 
           discrete   = 'age_bucket',
           open_ended = expr(starts_with('age_OE')), # add later
           continuous = 'age_est',
           NA
  ),
  # HH_Income
  switch(demos.bucket_type,
         discrete   = 'hhincome_cat',
         open_ended = expr(starts_with('hhincome_OE')), # add later
         continuous = 'hhincome_est',
         NA
  ),
  'hhsize', 
  # Education
  switch(demos.bucket_type, 
         discrete   = 'education',
         open_ended = expr(starts_with('education_OE')), # add later
         continuous = 'education',
         NA),
  # Sex
  'sex' = if_else(demos.consolidate_vars, 'sex_consolidated', 'sex'), 
  # Race
  'race' = if_else(demos.consolidate_vars, 'race_consolidated', 'race'), 
  # Home_Ownership
  'homeown', 
  # Young Children
  'youngchildren'
)

#demo_quo <- quo(!!!demo_controls)
df.clean %>% select(!!!demo_controls)
```
